### ISSUE TITLE
Filters fails when `/` character is present in the key

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-k8s-metrics-adapter#24]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Adding a match label with special character `/` makes the NRQL query to bring no matches.

## Steps to Reproduce
```yaml
    - type: External
      external:
        metric:
          name: k8s.container.cpuCoresUtilization 
          selector:
            matchLabels: 
              tags.app.kubernetes.io/name: nginx
        target:
          type: AverageValue 
          value: 25
```
this is transformed to 
```
SELECT average(`k8s.container.cpuCoresUtilization`) FROM Metric SINCE 2 MINUTES AGO where clusterName='xx' where tags.app.kubernetes.io/name = 'nginx'
```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
Should be  transformed to:
```
SELECT average(`k8s.container.cpuCoresUtilization`) FROM Metric SINCE 2 MINUTES AGO where clusterName='xx' where `tags.app.kubernetes.io/name` = 'nginx'
```
[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )
