### ISSUE TITLE
Default cluster filter doesn't cover clusterName alias attributes.

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-k8s-metrics-adapter#31]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

External metrics queries are being filtering by the clusterName by default unless the `removeClusterFilter` parameter is set. This automatic default filter is [adding](https://github.com/newrelic/newrelic-k8s-metrics-adapter/blob/c1f970cdb572de8533c4f1a2bfde6fdb251cd02f/internal/provider/newrelic/query.go#L26) the `where clusterName=<cluster name>` clause to the query. The issue is that the `clusterName` attribute has some aliases depending on the source of the data and type, following some examples:
- Metrics coming from Pixie is`k8s.cluster.name`
- Metrics transformed to Dimensional Metrics `k8s.clusterName`

Because of this reason the current filter only work for metrics comming from the Infra Agent or on-host integrations when using samples.

## Desired Behavior

All aliases are contemplated in the filter and is transparent for the point of view of configuration. 

## Possible Solution

We could add a where condition that covers all alias like:
`where (clusterName=<cluster name> OR k8s.cluster.name=<cluster name> OR k8s.clusterName=<cluster name>)`

## Additional context
The current workaround is to disable the cluster filter by  activating `removeClusterFilter`, and to use custom filters depending on the source.

**Comment by tsurankov** [comment]
I don't really understand what component needs to be enabled for clusterName to work.
For example, my helm chart values are the following:
```
newrelic-infrastructure:
  enabled: true
nri-prometheus:
  enabled: false
nri-metadata-injection:
  enabled: true
kube-state-metrics:
  enabled: true
  collectors:
    certificatesigningrequests: false
    ingresses: false
nri-kube-events:
  enabled: false
newrelic-logging:
  enabled: false
newrelic-pixie:
  enabled: false
pixie-chart:
  enabled: false
newrelic-infra-operator:
  enabled: false
newrelic-k8s-metrics-adapter:
  enabled: true
```
newrelic-infrastructure component is enabled, however, in NRQL I can see only k8s.clusterName filter is available.

This is annoying because I use external metrics and have to set removeClusterFilter: true and specify k8s.clusterName explosively in each HPA definition
