### ISSUE TITLE
[Question] Possibility to send query to API from another namespace

### ISSUE THREAD

**Issue by doctornkz** [newrelic/newrelic-k8s-metrics-adapter#62]
Good day, team! I have a question to you. 

Nowadays we are using very old newrelic-adapter fork which allows to get metric from dedicated namespaces. Several HPAs get external metric from only one instance of newrelic-adapter.  
As example, in project namespace we have ExternalMetric resource :
```
apiVersion: metrics.newrelic/v1alpha1
kind: ExternalMetric
metadata:
  labels:
    app.kubernetes.io/instance: my_project
  name: active-connections
  namespace: my_project
spec:
  name: my_project
  queries:
    - id: active-connections
      query: >-
        SELECT rate(sum(aws.applicationelb.ActiveConnectionCount), 1 minute) as
        'active' FROM Metric WHERE `collector.name` =
        'cloudwatch-metric-streams' AND `aws.accountId` = '*******' since 5 minutes ago
  resource:
    resource: deployment
```
In HPA manifest we have a specific section: 
```
  metrics:
    - external:
        metric:
          name: active-connections
        target:
          averageValue: 100
          type: AverageValue
```
As you see developers can use adapter from isolated namespace without reconfiguring newrelic-adapter itself. And newrelic-adapter application is sending results of query to other namespace.

As I got from current documentation I have to use configmap inside newrelic-adapter namespace (with defined query) and use name of that query from HPAs namespace. It's not very useful, I prefer to give opportunity to define query on project side. Did I miss something in documentation or it's not implemented? 
Documentation: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/newrelic-metrics-adapter/

Thank you!

**Comment by gsanchezgavier** [comment]
Hi @doctornkz this metric-adapter doesn't filter by namespace,  metrics should be available for HPAs on any namespace. 
Thanks!

**Comment by doctornkz** [comment]
Thank you for response, @gsanchezgavier . I believe I didn't explain myself well. I am very sorry.
My question is - can I send plain NRQL query to metric-adapter API? With your implementation I am sending the `name` of query from HPA : 
```
  metrics:
    - type: External
      external:
        metric:
          name: nginx_average_requests
```
and metric-adapter is using local configmap to  translate the `name` to NRQL, call the NR API, fetch the result and send it to HPA back. It's not flexible, because I have to configure external metrics integration on both sides - my project HPA and metric-adapter configmap. 

Is it possible instead of sending the `name` object to send `query` object with NRQL string ? Like this: 
```
spec:
  name: my_project
  resource:
    resource: "deployment"
  queries:
    - id: visible-messages
      query: "SELECT max(aws.sqs.ApproximateNumberOfMessagesVisible) AS 'visible' FROM Metric WHERE `aws.sqs.QueueName`= my_sqs_queue' since 10 minutes ago"
```
in this case I am not touching metric-adapter, I am sending to API plain NRQL string and adapter is just requesting NR API with that exact query. It seems more flexible and simpler to manage. 
Proof of concept [here](https://github.com/kuperiu/k8s-newrelic-adapter/blob/master/pkg/apis/metrics/v1alpha1/externalmetric.go#L35-L68)
Thank you again.

**Comment by gsanchezgavier** [comment]
Hi @doctornkz , thanks for the detailed explanation, I got your question now.
> can I send plain NRQL query to metric-adapter API? 

This is not supported, as you mentioned queries are pre-defined from config.

On the other hand the metric-adapter is using the metric selector from the HPA  as NRQL condition which can bring some flexibility for any HPA using the same metric but with different scope. 

Imagine you define a metric like this (without the filter):

```
# section from metrics adapter config
externalMetrics:
      visible-messages:
        query: "SELECT max(aws.sqs.ApproximateNumberOfMessagesVisible) AS 'visible' FROM Metric SINCE 20 MINUTES AGO"
```
Then HPA could add the queue name filter by selectors like this:
```
# section from HPA
metrics:
    - type: External
      external:
        metric:
          name: visible-messages
          selector:
            matchLabels:
              aws.sqs.QueueName: my_sqs_queue
```

But for sure this not cover the main use cases you mentioned here

> As you see developers can use adapter from isolated namespace without reconfiguring newrelic-adapter itself. And newrelic-adapter application is sending results of query to other namespace.

I will mark this issue as a feature request.
