### ISSUE TITLE
CRD for defining external metrics

### ISSUE THREAD

**Issue by alec-pinson** [newrelic/newrelic-k8s-metrics-adapter#81]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Currently we need to define metrics as follows:-

```yaml
    externalMetrics:
      dev_nginx_average_requests:
        query: "FROM Metric SELECT average(nginx.server.net.requestsPerSecond) WHERE label.environment = 'dev' SINCE 2 MINUTES AGO"
      test_nginx_average_requests:
        query: "FROM Metric SELECT average(nginx.server.net.requestsPerSecond) WHERE label.environment = 'test' SINCE 2 MINUTES AGO"
      dynamic_env1_nginx_average_requests:
        query: "FROM Metric SELECT average(nginx.server.net.requestsPerSecond) WHERE label.environment = 'dynamic_env1' SINCE 2 MINUTES AGO"
      dynamic_env2_nginx_average_requests:
        query: "FROM Metric SELECT average(nginx.server.net.requestsPerSecond) WHERE label.environment = 'dynamic_env2' SINCE 2 MINUTES AGO"
```

We have dynamic environments that are spun up and spun down constantly. The problem we have is that we have to update the single New Relic config for each environment that's added/removed.  

## Desired Behavior

Option to use a CRD to define external metrics

```yaml
apiVersion: newrelic.com/v1beta1
kind: externalMetric
metadata:
  name: dev_nginx_average_requests
spec:
  query: FROM Metric SELECT average(nginx.server.net.requestsPerSecond) WHERE label.environment = 'dev' SINCE 2 MINUTES AGO
```

## Additional context

Due to the fact we deploy various environments within a cluster we need various metrics available to each environment. The above solution would allow us to deploy external metrics along side each environment.

**Comment by alec-pinson** [comment]
Nevermind I realised you can do the following instead:-

```yaml
    externalMetrics:
      nginx_average_requests:
        query: "FROM Metric SELECT average(nginx.server.net.requestsPerSecond) SINCE 2 MINUTES AGO"
```
```yaml
  - type: External
    external:
      metric:
        name: nginx_average_requests
        selector:
          matchLabels:
            label.environment: dev
```
