### ISSUE TITLE
Support matchLabels

### ISSUE THREAD

**Issue by invidian** [newrelic/newrelic-k8s-metrics-adapter#9]
From metrics-adapter created by [paologallinaharbur](https://github.com/paologallinaharbur): gsanchezgavier/metrics-adapter#14  

The docs states:

```
     matchLabels is a map of {key,value} pairs. A single {key,value} in the
     matchLabels map is equivalent to an element of matchExpressions, whose key
     field is "key", the operator is "In", and the values array contains only
     "value". The requirements are ANDed.
```

Even if it is equivalent to a `matchExpressions` with a `IN` clause, it is passed using the equal operator `=` in 1.21

Now we are getting the following error:
```
ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric nginx/test1/&LabelSelector{MatchLabels:map[string]string{testA: teSt,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: getting metric value: building query: requirement 0 use unsupported operator "="
```
with
```
  - type: External
    external:
      metric:
        name: test1
        selector:
          matchLabels: 
            testA: teSt
```

We should add back the `=` operator
